function out1 = clc_H(q1, q2, vq1, vq2, Lb1, Lb2, Mb1, Mb2, Ixb1, Iyb1, Izb1, Ixb2, Iyb2, Izb2, fm1, fm2, foutil, G)
  %CLC_H  Autogenerated by sympy
  %   Code generated with sympy 1.1.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = [G.*Lb1.*Mb1.*cos(q1)/2 + G.*Mb2.*(Lb1.*cos(q1) + Lb2.*cos(q1 + q2)/2) + Mb2.*vq2.*(-2*Lb1.*Lb2.*vq1.*sin(q2) - Lb1.*Lb2.*vq2.*sin(q2))/2 + fm1.*vq1 + foutil.*(2*Lb1.^2.*vq1 + 4*Lb1.*Lb2.*vq1.*cos(q2) + 2*Lb1.*Lb2.*vq2.*cos(q2) + 2*Lb2.^2.*vq1 + 2*Lb2.^2.*vq2)/2; G.*Lb2.*Mb2.*cos(q1 + q2)/2 - Lb1.*Lb2.*Mb2.*vq1.*vq2.*sin(q2)/2 - Mb2.*(-Lb1.*Lb2.*vq1.^2.*sin(q2) - Lb1.*Lb2.*vq1.*vq2.*sin(q2))/2 + fm2.*vq2 + foutil.*(2*Lb1.*Lb2.*vq1.*cos(q2) + 2*Lb2.^2.*vq1 + 2*Lb2.^2.*vq2)/2];

end
